using System;
using System.IO;
using System.Text;
using Base.Interfaces;

namespace Imp.Report
{
    /// <summary>
    /// Report generated by an Authorized personnel
    /// </summary>
    public class HTMLReportDecorator : IReport
    {
        /// <summary>
        /// Internal Sales report
        /// </summary>
        private IReport report;

        /// <summary>
        /// Name of Product
        /// </summary>
        public string ProductName { get { return report.ProductName; } }
        /// <summary>
        /// Average Weekly Sales Revenue
        /// </summary>
        public string AverageWeeklySalesRevenue { get { return report.AverageWeeklySalesRevenue; } }
        /// <summary>
        /// Profit Year to Date
        /// </summary>
        public string ProfitYTD { get { return report.ProfitYTD; } }
        /// <summary>
        /// Percentage of Opportunities converted to Sales
        /// </summary>
        public string PercentageOppToSales { get { return report.PercentageOppToSales; } }
        /// <summary>
        /// Name
        /// </summary>
        private string HtmlFilePath { get; set; }
        /// <summary>
        /// ctor
        /// </summary>
        public HTMLReportDecorator(IReport decoratee, string htmlFilePath)
        {
            report = decoratee;
            HtmlFilePath = htmlFilePath;
        }
        /// <summary>
        /// Generate Report
        /// </summary>
        /// <returns></returns>
        public string GenerateReport()
        {
            string reportText = report.GenerateReport();
            StoreHTMLReport(reportText);
            return reportText;
        }
        /// <summary>
        /// Store the Report in HTML format
        /// </summary>
        /// <param name="report"></param>
        private void StoreHTMLReport(string report)
        {
            string htmlContent = GenerateHTMLContent(report);
            File.WriteAllText(HtmlFilePath, htmlContent);
        }
        /// <summary>
        /// Generate HTML Content for the report
        /// </summary>
        /// <param name="report"></param>
        /// <returns></returns>
        private string GenerateHTMLContent(string report)
        {
            // Use a HTML Template, fill the report data here and decorate the Report content in a presentable way
            return report;
        }
    }
}
