using System;
using System.Text;
using Base.Interfaces;

namespace Imp.Report
{
    /// <summary>
    /// Report generated by an Authorized personnel
    /// </summary>
    public class SalesManagerReportDecorator : IReport
    {
        /// <summary>
        /// Internal Sales report
        /// </summary>
        private IReport report;

        /// <summary>
        /// Name of Product
        /// </summary>
        public string ProductName { get { return report.ProductName; } }
        /// <summary>
        /// Average Weekly Sales Revenue
        /// </summary>
        public string AverageWeeklySalesRevenue { get { return report.AverageWeeklySalesRevenue; } }
        /// <summary>
        /// Profit Year to Date
        /// </summary>
        public string ProfitYTD { get { return report.ProfitYTD; } }
        /// <summary>
        /// Percentage of Opportunities converted to Sales
        /// </summary>
        public string PercentageOppToSales { get { return report.PercentageOppToSales; } }
        /// <summary>
        /// Name
        /// </summary>
        private string ManagerName { get; set; }
        /// <summary>
        /// ctor
        /// </summary>
        public SalesManagerReportDecorator(IReport decoratee, string salesManagerName)
        {
            report = decoratee;
            ManagerName = salesManagerName;
        }
        /// <summary>
        /// Generate Report
        /// </summary>
        /// <returns></returns>
        public string GenerateReport()
        {
            string reportText = report.GenerateReport();
            StringBuilder builder = new StringBuilder();
            builder.AppendLine("--------------------------------------------------------------");
            builder.AppendLine(string.Format("Date : {0}", DateTime.Now.Date.ToShortDateString()));
            builder.AppendLine(string.Format("Report Prepared By : {0}", ManagerName));
            builder.AppendLine("--------------------------------------------------------------");
            builder.AppendLine(reportText);
            builder.AppendLine("--------------------------------------------------------------");

            return builder.ToString();
        }
    }
}
